# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d488c49264a75be44d81fca7d42053e212e009aad6ce095e874e18deb2c76ae25258693cedf0b9135f7bab5681d1eb161df3be18b078ecc8d843fb03d793357

test:
  secret_key_base: 889bed8abaf8d882f0348df2ab91c963825e9dd6062c1fb5525b91fb93f41891707a39dd3d8d9d61102f1247dffa53cc67329b8f4c7a6cfe1b05ca9c86c39940

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
